# Generated by scripts/package-maintenance.sh new. Replace TODO values, then
# run: scripts/package-maintenance.sh prefetch NAME
{ callPackage, lib }:

(callPackage ./lib/mkGitHubTool.nix { }) {
  pname = "@NAME@";
  version = "0-unstable-@DATE@";
  build = "go";
  source = {
    owner = "@OWNER@";
    repo = "@REPO@";
    updateBranch = "@BRANCH@";
    rev = "@REV@";
    hash = lib.fakeHash;
  };
  vendorHash = lib.fakeHash;
  subPackages = [ ];
  description = "TODO: describe @NAME@";
  license = "mit";
}
